<a href="https://colab.research.google.com/github/everjava/sctech/blob/main/Semana_2_Modelo_IA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import seaborn as sns  # Biblioteca de visualização que possui datasets de estudo embutidos
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [ ]:
df = sns.load_dataset('iris')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
X_estudo = df[['sepal_width','sepal_length','petal_width','petal_length']]
y_estudo = df['species']

X_treino, X_teste, y_treino, y_teste = train_test_split(X_estudo, y_estudo, test_size=0.20, random_state=42)

In [ ]:
# Vamos usar o algoritmo de Árvore de Decisão
modelo_final = DecisionTreeClassifier(max_depth=3)
modelo_final.fit(X_treino, y_treino) # A MÁGICA ACONTECE NO FIT!
print("IA Treinada com sucesso!")

IA Treinada com sucesso!


In [ ]:
modelo_final.fit(X_treino, y_treino)

# 4. Predições
y_pred = modelo_final.predict(X_teste)

from sklearn.datasets import load_iris
iris = load_iris()
X, y = iris.data, iris.target
# 5. Métricas de Avaliação
print("Acurácia:", accuracy_score(y_teste, y_pred))
print("\nMatriz de Confusão:\n", confusion_matrix(y_teste, y_pred))
print("\nRelatório de Classificação:\n", classification_report(y_teste, y_pred, target_names=iris.target_names))

Acurácia: 1.0

Matriz de Confusão:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Relatório de Classificação:
               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

